version: '3.9'

services:
  nginx:
    build: 
      dockerfile: ./nginx/Dockerfile 
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./nginx/kbfira_docs:/var/www/kbfira_docs/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kbv2-fira-net
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    networks:
      - kbv2-fira-net

networks:
  kbv2-fira-net:
    driver: bridge